### PR TITLE
Bug fixes: syntax plus openCV version check fix

### PR DESCRIPTION
**Pull request by uzair004**
* check if OpenCV 2.X or later is installed instead of looking for exactly 2.X version
* syntax error fix in debug print

### CODE REVIEW

**Comment by renaldfredy** [comment]
I got error "Model Error: Model 'UNetRNN' import failed, please check the model file."

Could you help what's going on since I checked there is no UNetRNN?

Thank you

**Comment by uzair004** [comment]
are you using the exact code from this pull request? I am using it with no issues so far, I haven't touched model-related files in PR. can you double check & verify if you have done some local changes to those files

**Comment by renaldfredy** [comment]
!python /content/rectify.py /content/example/ /content/result

I have done with my problem since I ran in google colab, so I supposed to copy all files and paste beyond the folder from git clone. However, I got problem with the result in below. Would you explain me why my picture could not be rectified ? Thank you.

[1/2] Failed. card1.jpg could not be rectified :(
[2/2] Failed. card2.jpg could not be rectified :(
Done! 0/2 success.

**Comment by uzair004** [comment]
> !python /content/rectify.py /content/example/ /content/result
> 
> I have done with my problem since I ran in google colab, so I supposed to copy all files and paste beyond the folder from git clone. However, I got a problem with the result in below. Would you explain me why my picture could not be rectified ? Thank you.
> 
> [1/2] Failed. card1.jpg could not be rectified :( [2/2] Failed. card2.jpg could not be rectified :( Done! 0/2 success.

In the rectify.py file set `debug = True` & create debug folder in the home directory, you will get the exact message why your image wasn't rectified, i.e corners cannot be detected.
make sure you are using code from this PR instead of the main/master branch.

**Comment by renaldfredy** [comment]
Thank you, I have conducted what you instructed me. Everything was fine when I used card data from your PR, but I got problem when I want to rectify QR code images. Is this program only be used for card rectification?

**Comment by uzair004** [comment]
> Thank you, I have conducted what you instructed me. Everything was fine when I used card data from your PR, but I got a problem when I want to rectify QR code images. Is this program only be used for card rectification?

most probably, Yes. @shakex can comment on that.

**Comment by shakex** [comment]
> Thank you, I have conducted what you instructed me. Everything was fine when I used card data from your PR, but I got problem when I want to rectify QR code images. Is this program only be used for card rectification?

yes, it does not support to rectify QR code image yet.

**Pull request merged**
